name: Unit Tests
description: Run unit tests with coverage reporting

runs:
  using: composite
  steps:
    - name: Run Tests with Coverage
      shell: bash
      run: pnpm test:coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: always()
      with:
        token: ${{ env.CODECOV_TOKEN }}

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ env.CODECOV_TOKEN }}
