name: Setup PNPM and Node.js
description: Setup PNPM, node, and install dependencies

runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: pnpm
        registry-url: https://registry.npmjs.org

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
