name: 🚀 Feature Request
description: Suggest a new feature or enhancement for tsc-files
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We appreciate your ideas for improving tsc-files.

        **Before submitting**, please check:
        - [ ] This feature doesn't already exist
        - [ ] You've checked existing feature requests for duplicates
        - [ ] This aligns with the project's goals (TypeScript file checking for git hooks and CI/CD)

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: "I'm always frustrated when... / It would be helpful if... / Currently there's no way to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: 'I would like tsc-files to... / The feature should work by...'
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases and scenarios where this feature would be valuable
      placeholder: |
        1. When working with monorepos...
        2. In CI/CD pipelines...
        3. For git hooks...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: Show how you envision using this feature (CLI commands, configuration, etc.)
      placeholder: |
        ```bash
        # Example command
        tsc-files --new-feature src/**/*.ts
        ```
      render: markdown
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternative solutions or workarounds you've considered
      placeholder: 'I considered using... / Another approach could be... / Currently I work around this by...'
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - 'Low - nice to have'
        - 'Medium - would be helpful'
        - 'High - significantly improves workflow'
        - 'Critical - blocking current usage'
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area of tsc-files would this feature affect?
      options:
        - 'CLI interface'
        - 'Configuration handling'
        - 'Package manager detection'
        - 'TypeScript integration'
        - 'Error reporting'
        - 'Performance'
        - 'Documentation'
        - 'Other'
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: 'Any additional information, links to similar features in other tools, etc.'
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
