name: Integration Tests
description: Run integration tests

runs:
  using: composite
  steps:
    - name: Run Integration Tests
      shell: bash
      run: |
        echo "🧪 Running Vitest integration suite (project=integration)..."
        pnpm test:integration
