name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Package
        uses: ./.github/actions/build-package

      - name: Test CLI Installation
        run: |
          npm pack
          npm install -g ./jbabin91-tsc-files-*.tgz

      - name: Test CLI Usage
        run: |
          echo 'console.log("test");' > test.ts
          tsc-files test.ts
          echo 'const x: string = 123;' > error.ts
          tsc-files error.ts || echo "Expected error caught"

      - name: Test with Different Package Managers
        run: |
          # Test with different package managers in temp directories
          mkdir -p /tmp/test-npm && cd /tmp/test-npm
          npm init -y
          npm install typescript
          echo 'const x: number = "string";' > test.ts
          npx tsc-files test.ts || echo "npm test passed"
