name: Release

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [main]
  workflow_dispatch:
    inputs:
      enable_debug:
        type: boolean
        description: 'Enable debug logging'
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  ACTIONS_STEP_DEBUG: ${{ github.event_name == 'workflow_dispatch' && inputs.enable_debug }}

jobs:
  release:
    name: Release
    if: github.repository == 'jbabin91/tsc-files' && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/actions/setup

      - name: Set NPM Token
        shell: bash
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.5.3
        with:
          publish: pnpm changeset:release
          version: pnpm changeset:version
          commit: 'chore(release): :hammer: version package'
          title: 'chore(release): :hammer: version package'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
